os: osx
osx_image: xcode8
sudo: required
language: generic

install:
    - "./build.sh"

deploy:
  provider: releases
  api_key:
    secure: TqRfm2Hh4p0uD3GNaVElvK/P09P+FyTqXGF5ifgd+RW3TfYEjUKH8enxA7HV8bWSa1Hst4OUupdUavk9AAEZ99iLaLXCQwatSIZvo3hi7KHQ9q2M856FfhNTk1hUr53EocQjW1/ECUR3kG7dkihi08r2EsoDnmLiOhBxfst3e2CVS0jMVcSvKqxsMGyI8SUvAvYIT35B+udOC0ivOqlF3OMRbU79jvyteplyUbZxkB27oRDqFMnOtEqmz0D5k6AM+P9BUxZHuFd1tVxmoflMJoFAvJYlYFL8+PC4r1GfGhbRXMKPW5av8IWjQyRS15b1QsrFs0PyeonqPb4PtMvInpk6BYAwWgC0qYZtpSRsi8SNES/PYFfwArjw1ZmIBf/pxpXN4+TeMSVq6Z+F/1eDT4JPcoW4y2CRZJQ0CSB2n10yUmMIPogy1wEwVkveZsU64CnGIJQmDaL/77sA/KRUdXz8J2rByILhFZATCRW2pLg2rfkyZdjwKHPl+ozs+3Ea4q9svmbcaZCulcVEHYMkOtD1288DTxrC1d1Mw2VRlVDleNK3JHcdz89duFvVz5iF63kRtkK81z4kOPvYz7zV1R16IBa/5IX2QeLXsjJDO84umunpAYBZfcvI7AJsn4bnnmDfudUtBrri9/aZJvqTuXbWhOOntzqSbCDdFncvaPw=
  file: platform_darwin64.tar.gz
  on:
    repo: 2620/openmedialibrary_darwin_build
